const $ = (s) => document.querySelector(s);
const historyKey = 'plw-history-v1';
const state = { lang: localStorage.getItem('plw-lang') || 'en' };
const translations = {
  en:{eyebrow:'FIELD TOOL · PAKISTAN',headline:'Know the animal.<br><em>Know the weight.</em>',intro:'A refined field calculator for estimating livestock live weight from body measurements.',stepAnimal:'Animal',stepMeasure:'Measure',stepResult:'Result',estimate:'LIVE WEIGHT ESTIMATE',measureAnimal:'Measure your animal',animalType:'Animal type',cattle:'Cattle',buffalo:'Buffalo',sheep:'Sheep',goat:'Goat',heartGirth:'Heart girth',bodyLength:'Body length',girthHelp:'Measure around the chest, just behind the front legs.',lengthHelp:'Shoulder point to the base of the tail.',calculate:'Calculate estimated weight',resultKicker:'ESTIMATED LIVE WEIGHT',share:'Share result',estimateNote:'This is an estimate. Actual live weight can vary with breed, condition and measurement accuracy.',recent:'RECENT',history:'Calculation history',clear:'Clear',noHistory:'Your recent calculations will appear here.',footerNote:'For estimation purposes only'},
  ur:{eyebrow:'فیلڈ ٹول · پاکستان',headline:'جانور کو سمجھیں۔<br><em>وزن کا اندازہ لگائیں۔</em>',intro:'جسمانی پیمائش کے ذریعے مویشی کے زندہ وزن کا تخمینہ لگانے کے لیے ایک جدید فیلڈ کیلکولیٹر۔',stepAnimal:'جانور',stepMeasure:'پیمائش',stepResult:'نتیجہ',estimate:'زندہ وزن کا تخمینہ',measureAnimal:'اپنے جانور کی پیمائش کریں',animalType:'جانور کی قسم',cattle:'گائے',buffalo:'بھینس',sheep:'بھیڑ',goat:'بکری',heartGirth:'سینے کا گھیر',bodyLength:'جسم کی لمبائی',girthHelp:'اگلی ٹانگوں کے پیچھے سینے کے گرد پیمائش کریں۔',lengthHelp:'کندھے سے دم کے شروع تک پیمائش کریں۔',calculate:'وزن کا تخمینہ لگائیں',resultKicker:'زندہ وزن کا تخمینہ',share:'نتیجہ شیئر کریں',estimateNote:'یہ صرف ایک تخمینہ ہے۔ نسل، جسمانی حالت اور پیمائش کی درستگی کے باعث اصل وزن مختلف ہو سکتا ہے۔',recent:'حالیہ',history:'حساب کی تاریخ',clear:'صاف کریں',noHistory:'آپ کے حالیہ حساب یہاں نظر آئیں گے۔',footerNote:'صرف تخمینہ کے لیے'}
};
function applyLanguage(){const t=translations[state.lang];document.documentElement.lang=state.lang;document.documentElement.dir=state.lang==='ur'?'rtl':'ltr';document.body.classList.toggle('rtl',state.lang==='ur');document.querySelectorAll('[data-i18n]').forEach(el=>el.innerHTML=t[el.dataset.i18n]||el.innerHTML);$('#languageToggle').textContent=state.lang==='en'?'اردو':'English'}
function estimateWeight(animal,girth,length){/* The source repository contains no implemented calculation engine. Keep this estimator isolated so a verified business formula can replace it without touching UI/history. */const base=(girth*girth*length)/10840;const factors={cattle:1,buffalo:1.08,sheep:.22,goat:.20};return Math.max(1,base*(factors[animal]||1))}
function getHistory(){try{return JSON.parse(localStorage.getItem(historyKey)||'[]')}catch{return []}}
function saveHistory(item){const items=[item,...getHistory()].slice(0,10);localStorage.setItem(historyKey,JSON.stringify(items));renderHistory()}
function renderHistory(){const list=$('#historyList'),items=getHistory();if(!items.length){list.innerHTML='<div class="empty-state" data-i18n="noHistory"></div>';applyLanguage();return}list.innerHTML=items.map(x=>`<div class="history-item"><div class="history-main"><strong>${escapeHtml(x.animal)}</strong><small>${x.girth} × ${x.length} in · ${escapeHtml(x.date)}</small></div><span class="history-weight">${x.weight} kg</span></div>`).join('')}
function escapeHtml(v){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]))}
function animalName(v){return translations[state.lang][v]||v}
$('#calculatorForm').addEventListener('submit',e=>{e.preventDefault();const animal=$('input[name="animal"]:checked').value,girth=Number($('#girth').value),length=Number($('#length').value),notice=$('#validation');if(!Number.isFinite(girth)||!Number.isFinite(length)||girth<=0||length<=0){notice.textContent=state.lang==='ur'?'براہ کرم درست پیمائش درج کریں۔':'Please enter valid measurements.';notice.hidden=false;return}notice.hidden=true;const weight=Number(estimateWeight(animal,girth,length).toFixed(1));$('#weightValue').textContent=weight;$('#animalLabel').textContent=animalName(animal);$('#measurementLabel').textContent=`${girth} × ${length} in`;$('#resultSection').hidden=false;$('#resultSection').scrollIntoView({behavior:'smooth',block:'start'});saveHistory({animal:animalName(animal),girth,length,weight,date:new Intl.DateTimeFormat(state.lang==='ur'?'ur-PK':'en-PK',{dateStyle:'medium',timeStyle:'short'}).format(new Date())})});
document.querySelectorAll('.animal-option input').forEach(i=>i.addEventListener('change',()=>document.querySelectorAll('.animal-option').forEach(x=>x.classList.toggle('selected',x.querySelector('input').checked))));
$('#clearHistory').addEventListener('click',()=>{localStorage.removeItem(historyKey);renderHistory()});
$('#themeToggle').addEventListener('click',()=>{document.body.classList.toggle('dark');localStorage.setItem('plw-theme',document.body.classList.contains('dark')?'dark':'light')});
$('#languageToggle').addEventListener('click',()=>{state.lang=state.lang==='en'?'ur':'en';localStorage.setItem('plw-lang',state.lang);applyLanguage();renderHistory()});
$('#shareButton').addEventListener('click',async()=>{const text=`Pakistan Livestock Weight\n${$('#animalLabel').textContent}: ${$('#weightValue').textContent} kg\n${$('#measurementLabel').textContent}`;try{if(navigator.share)await navigator.share({title:'Pakistan Livestock Weight',text});else await navigator.clipboard.writeText(text)}catch{}});
if(localStorage.getItem('plw-theme')==='dark')document.body.classList.add('dark');applyLanguage();renderHistory();if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
